language: node_js
node_js:
  - 0.10.x
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run coverage
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls